import { readFileSync, writeFileSync } from 'node:fs';
import { defaultContent } from '../src/data/siteContent';
import { gameSchema, settingsSchema } from '../src/lib/validation';

const quote = (value: unknown) => `'${String(value).replaceAll("'", "''")}'`;
const settings = settingsSchema.parse(defaultContent);
const games = defaultContent.games.map((game) => gameSchema.parse(game));
const sql = `-- Generated by npm run db:seed:generate. Initial sample content only.\n-- Idempotent: never replaces previously published content.\nbegin;\n\ninsert into public.site_settings (id, hero_image, logo_image, cta_links) values\n(true, ${quote(settings.heroImage)}, ${quote(settings.logoImage)}, ${quote(JSON.stringify(settings.ctaLinks))}::jsonb)\non conflict (id) do nothing;\n\ninsert into public.games (id, title, developer, category, description, accent_color, cover_image, cover_alt, walkthrough) values\n${games.map((game) => `(${[game.id, game.title, game.developer, game.category, game.description, game.accentColor, game.coverImage, game.coverAlt].map(quote).join(', ')}, ${quote(JSON.stringify(game.walkthrough))}::jsonb)`).join(',\n')}\non conflict (id) do nothing;\n\ncommit;\n`;
const path = 'supabase/migrations/20260906000200_seed_content.sql';
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== sql)
    throw new Error('Seed is out of date. Run npm run db:seed:generate.');
} else {
  writeFileSync(path, sql);
  console.log(`Wrote ${path}`);
}
