create table if not exists public.site_content (
  id text primary key default 'default',
  content jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

create policy "Anyone can read site content"
on public.site_content
for select
using (true);

create policy "Anyone can manage site content"
on public.site_content
for all
to anon, authenticated
using (true)
with check (true);

create table if not exists public.game_progress (
  id bigint generated by default as identity primary key,
  game_id text not null,
  step_ids text[] not null default '{}',
  updated_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  unique (user_id, game_id)
);

alter table public.game_progress enable row level security;

create policy "Users can manage their own progress"
on public.game_progress
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('site-images', 'site-images', true)
on conflict (id) do update set public = true;

create policy "Anyone can upload site images"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'site-images');
