create table if not exists public.site_content (
  id text primary key default 'default',
  content jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

create policy "Anyone can read site content"
on public.site_content
for select
using (true);

create policy "Authenticated users can manage site content"
on public.site_content
for all
to authenticated
using (true)
with check (true);

create table if not exists public.game_progress (
  id bigint generated by default as identity primary key,
  game_id text not null,
  step_ids text[] not null default '{}',
  updated_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  unique (user_id, game_id)
);

alter table public.game_progress enable row level security;

create policy "Users can manage their own progress"
on public.game_progress
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
