create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  text text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments for select
using (true);

drop policy if exists "Users can create their own comments" on public.comments;
create policy "Users can create their own comments"
on public.comments for insert
to authenticated
with check (auth.uid() = user_id);